name: Test

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        deno-version: [ 1.43.5 ]
        bun-version: [ 1.1.8 ]
        go-version: [ 1.22.3 ]
        hyperfine-version: [ 1.18.0 ]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: ${{ matrix.deno-version }}
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ matrix.bun-version }}

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install hyperfine on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        wget https://github.com/sharkdp/hyperfine/releases/download/v${{ matrix.hyperfine-version }}/hyperfine_${{ matrix.hyperfine-version }}_amd64.deb
        sudo dpkg -i hyperfine_${{ matrix.hyperfine-version }}_amd64.deb

    - name: Install hyperfine on macOS
      if: matrix.os == 'macos-latest'
      run: brew install hyperfine

    - name: Run benchmark
      run: deno task all

    - name: Show `report.md`
      run: cat report.md

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: report_on_${{ matrix.os }}
        path: report.md
